package io.aetheris.orchestrator.planner;

import io.aetheris.orchestrator.mission.*;
import io.aetheris.orchestrator.policy.OperationMode;
import io.aetheris.orchestrator.runtime.*;
import io.aetheris.orchestrator.scheduler.*;
import io.aetheris.orchestrator.task.*;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class MissionPlannerService {
    private final MissionService missions; private final MissionPlanNodeRepository nodes; private final TaskService tasks; private final DurableWorkQueueService queue; private final SchedulerService scheduler;
    public MissionPlannerService(MissionService missions,MissionPlanNodeRepository nodes,TaskService tasks,DurableWorkQueueService queue,SchedulerService scheduler){this.missions=missions;this.nodes=nodes;this.tasks=tasks;this.queue=queue;this.scheduler=scheduler;}
    @Transactional public List<MissionPlanNodeEntity> plan(UUID missionId,PlanMissionRequest request){missions.required(missionId);if(request.steps().isEmpty())throw new IllegalArgumentException("Mission plan requires at least one step");Map<String,PlanStepRequest> byKey=new LinkedHashMap<>();for(PlanStepRequest step:request.steps()){if(step.key()==null||step.key().isBlank()||step.title()==null||step.title().isBlank()||step.command()==null||step.command().isBlank())throw new IllegalArgumentException("Each mission step requires key, title and command");String key=step.key().trim();if(byKey.putIfAbsent(key,step)!=null)throw new IllegalArgumentException("Duplicate mission step key: "+key);}for(Map.Entry<String,PlanStepRequest> e:byKey.entrySet())for(String dep:e.getValue().dependsOn()){if(!byKey.containsKey(dep))throw new IllegalArgumentException("Unknown dependency '"+dep+"' for step "+e.getKey());if(dep.equals(e.getKey()))throw new IllegalArgumentException("Mission step cannot depend on itself: "+dep);}assertAcyclic(byKey);OperationMode mode=request.mode()==null?OperationMode.BALANCED:request.mode();Map<String,TaskEntity> taskByKey=new LinkedHashMap<>();for(Map.Entry<String,PlanStepRequest> e:byKey.entrySet()){PlanStepRequest step=e.getValue();TaskEntity task=tasks.create(new CreateTaskRequest(step.title().trim(),step.command().trim(),mode));missions.attach(missionId,task.getId());taskByKey.put(e.getKey(),task);}List<MissionPlanNodeEntity> created=new ArrayList<>();for(Map.Entry<String,PlanStepRequest> e:byKey.entrySet()){PlanStepRequest step=e.getValue();List<UUID> deps=step.dependsOn().stream().map(k->taskByKey.get(k).getId()).toList();created.add(nodes.save(new MissionPlanNodeEntity(UUID.randomUUID(),missionId,e.getKey(),taskByKey.get(e.getKey()).getId(),deps,step.priority(),step.agentId())));}return created;}
    public List<MissionPlanNodeEntity> nodes(UUID missionId){missions.required(missionId);return nodes.findByMissionIdOrderByPriorityDescCreatedAtAsc(missionId);}
    @Transactional public List<MissionPlanNodeEntity> releaseReady(UUID missionId){missions.required(missionId);List<MissionPlanNodeEntity> list=nodes.findByMissionIdOrderByPriorityDescCreatedAtAsc(missionId);for(MissionPlanNodeEntity node:list){TaskState state=tasks.getRequired(node.getTaskId()).getState();if(state==TaskState.COMPLETED){node.completed();nodes.save(node);continue;}if(state==TaskState.FAILED||state==TaskState.CANCELLED){node.failed();nodes.save(node);continue;}if(node.getState()==MissionPlanNodeState.BLOCKED){boolean ready=node.getDependencyTaskIds().stream().map(tasks::getRequired).allMatch(t->t.getState()==TaskState.COMPLETED);if(ready){node.ready();nodes.save(node);}}if(node.getState()==MissionPlanNodeState.READY){TaskEntity task=tasks.getRequired(node.getTaskId());if(task.getState()==TaskState.QUEUED)tasks.transition(task.getId(),new TaskTransitionRequest(TaskState.PLANNING,node.getAgentId(),"Mission dependency graph released step "+node.getStepKey()));WorkItemEntity item=queue.enqueue(new EnqueueWorkItemRequest(node.getTaskId(),"MISSION_STEP","{\"stepKey\":\""+escape(node.getStepKey())+"\"}",3));scheduler.schedule(new ScheduleWorkRequest(item.getId(),node.getPriority(),"mission"));node.enqueued();nodes.save(node);}}return nodes.findByMissionIdOrderByPriorityDescCreatedAtAsc(missionId);}
    private void assertAcyclic(Map<String,PlanStepRequest> steps){Set<String> visiting=new HashSet<>(),done=new HashSet<>();for(String key:steps.keySet())visit(key,steps,visiting,done);}private void visit(String key,Map<String,PlanStepRequest> steps,Set<String> visiting,Set<String> done){if(done.contains(key))return;if(!visiting.add(key))throw new IllegalArgumentException("Mission plan contains a dependency cycle at "+key);for(String dep:steps.get(key).dependsOn())visit(dep,steps,visiting,done);visiting.remove(key);done.add(key);}private String escape(String value){return value.replace("\\","\\\\").replace("\"","\\\"");}
}
