package io.aetheris.orchestrator.planner;

import io.aetheris.orchestrator.agent.*;import io.aetheris.orchestrator.model.*;import io.aetheris.orchestrator.policy.OperationMode;import org.springframework.stereotype.Service;import java.util.*;
@Service
public class MissionPlanProposalService {
 private final ModelExecutionService models;private final MissionPlannerService planner;private final AgentCatalogService agents;
 public MissionPlanProposalService(ModelExecutionService models,MissionPlannerService planner,AgentCatalogService agents){this.models=models;this.planner=planner;this.agents=agents;}
 public MissionPlanProposalResult propose(UUID missionId,MissionPlanProposalRequest r){String objective=require(r.objective());OperationMode mode=r.mode()==null?OperationMode.BALANCED:r.mode();String prompt="Create a safe dependency-aware mission plan for: "+objective+"\nReturn ONLY lines: STEP|key|title|agentId|priority|commaSeparatedDependencies|command\nUse existing Syntra/Aetheris specialist agent ids. Never propose destructive actions, live-money trading, withdrawal, credential theft, disabling safety, or unrestricted shell execution.";ModelExecutionResponse response=models.execute(new ModelExecutionRequest(null,"executive-planner",prompt,null,ModelClass.REASONING,mode,r.protectedData(),r.allowPaid()));if(response.status()!=ModelExecutionStatus.SUCCEEDED||response.response()==null)return new MissionPlanProposalResult(false,false,false,response.response(),List.of(),List.of(),response.detail());return validateAndMaybeMaterialize(missionId,response.response(),mode,r.materialize(),true);}
 public MissionPlanProposalResult validateRaw(UUID missionId,String raw,OperationMode mode,boolean materialize){return validateAndMaybeMaterialize(missionId,raw,mode==null?OperationMode.BALANCED:mode,materialize,false);}
 private MissionPlanProposalResult validateAndMaybeMaterialize(UUID missionId,String raw,OperationMode mode,boolean materialize,boolean modelSucceeded){List<String>warnings=new ArrayList<>();List<PlanStepRequest> steps=new ArrayList<>();if(raw==null||raw.isBlank())return new MissionPlanProposalResult(modelSucceeded,false,false,raw,List.of(),List.of(),"Empty plan");for(String line:raw.split("\\R")){String trimmed=line.trim();if(trimmed.isBlank())continue;if(!trimmed.startsWith("STEP|")){warnings.add("Ignored non-STEP line");continue;}String[] p=trimmed.split("\\|",7);if(p.length!=7){warnings.add("Malformed STEP line: "+trimmed);continue;}String key=p[1].trim(),title=p[2].trim(),agent=p[3].trim(),command=p[6].trim();int priority;try{priority=Math.max(0,Math.min(100,Integer.parseInt(p[4].trim())));}catch(Exception e){priority=50;warnings.add("Priority normalized for "+key);}Set<String> deps=new LinkedHashSet<>();if(!p[5].isBlank())for(String d:p[5].split(","))if(!d.isBlank())deps.add(d.trim());if(!agent.isBlank())agents.getRequired(agent);assertSafe(command);steps.add(new PlanStepRequest(key,title,command,agent,priority,deps));if(steps.size()>24)throw new IllegalArgumentException("Mission proposal exceeds 24 steps");}if(steps.isEmpty())return new MissionPlanProposalResult(modelSucceeded,false,false,raw,List.of(),warnings,"No valid STEP lines");validateGraph(steps);boolean made=false;if(materialize){planner.plan(missionId,new PlanMissionRequest(mode,steps));made=true;}return new MissionPlanProposalResult(modelSucceeded,true,made,raw,List.copyOf(steps),List.copyOf(warnings),made?"Validated and materialized":"Validated proposal; no tasks created");}
 private void validateGraph(List<PlanStepRequest> steps){Map<String,PlanStepRequest> m=new LinkedHashMap<>();for(PlanStepRequest s:steps){if(s.key()==null||s.key().isBlank()||m.putIfAbsent(s.key(),s)!=null)throw new IllegalArgumentException("Invalid or duplicate step key");}for(PlanStepRequest s:steps)for(String d:s.dependsOn())if(!m.containsKey(d)||d.equals(s.key()))throw new IllegalArgumentException("Invalid dependency "+d+" for "+s.key());Set<String> visiting=new HashSet<>(),done=new HashSet<>();for(String k:m.keySet())visit(k,m,visiting,done);}
 private void visit(String k,Map<String,PlanStepRequest> m,Set<String> visiting,Set<String> done){if(done.contains(k))return;if(!visiting.add(k))throw new IllegalArgumentException("Dependency cycle at "+k);for(String d:m.get(k).dependsOn())visit(d,m,visiting,done);visiting.remove(k);done.add(k);}private void assertSafe(String command){String c=command.toLowerCase(Locale.ROOT);for(String banned:List.of("live trade","withdraw","steal credential","disable safety","format disk","delete all","rm -rf /","bypass approval"))if(c.contains(banned))throw new IllegalArgumentException("Unsafe mission-plan command rejected: "+banned);}private String require(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Objective is required");return v.trim();}
}
