server:
  port: 8080

spring:
  application:
    name: aetheris-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Aetheris Gateway
    stage: 1.5
