import { Activity, Boxes, Gauge, LogOut, Network, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type User={id:number;name:string;email:string};
type Role='ADMIN'|'DEVELOPER'|'API_CONSUMER';
type Account={id:number;name:string;email:string;role:Role;scopes:string[]};
type AuthResponse={accessToken:string;refreshToken:string;tokenType:string;expiresInSeconds:number;refreshExpiresInSeconds:number;account:Account};
type Session={token:string;refreshToken:string;account:Account};
type Health='online'|'offline'|'checking';
type OrchestratorTask={id:string;title:string;state:string;mode:string;activeAgentId?:string|null;updatedAt:string};
type Approval={id:string;taskId:string;actionType:string;riskLevel:string;status:string;createdAt:string};
type ModelProvider={providerId:string;available:boolean;local:boolean;zeroCost:boolean;model:string;detail:string};
type ProviderHealth={providerId:string;successCount:number;failureCount:number;consecutiveFailures:number;averageLatencyMs:number;circuitOpen:boolean;circuitOpenUntil?:string|null;lastError?:string|null};
type ProviderBudget={providerId:string;unitsToday:number;dailyQuotaUnits:number;estimatedCostUsdToday:number;dailyBudgetUsd:number;allowed:boolean;detail:string};
type RateLimit={providerId:string;blocked:boolean;blockedUntil?:string|null;remainingUnits?:number|null;quotaResetAt?:string|null;reason?:string|null};
type Invocation={id:string;kind:string;targetId:string;status:string;agentId?:string|null;startedAt:string};
type EmergencyStop={active:boolean;changedAt:string;reason:string;cancelledTasks:number};
type WorkItem={id:string;taskId:string;workflowType:string;state:string;attempt:number;maxAttempts:number;leaseOwner?:string|null;leaseExpiresAt?:string|null;lastError?:string|null;updatedAt:string};
type Mission={id:string;title:string;objective:string;status:string;taskIds:string[];createdAt:string;updatedAt:string;liveStreamPath:string};
type Host={id:string;displayName:string;platform:string;status:string;capabilities:string[];lastSeenAt?:string|null};
type GitHubProposal={id:string;taskId?:string|null;repository:string;path:string;baseRef:string;summary:string;status:string;createdAt:string};
type McpServer={id:string;serverKey:string;displayName:string;status:string;local:boolean;enabled:boolean;approvedCapabilities:string[];allowedDataClasses:string[]};
type Worker={workerId:string;maxConcurrency:number;activeLeases:number;lastHeartbeatAt:string};
type SchedulerTicket={id:string;workItemId:string;priority:number;lane:string;state:string;createdAt:string};
type Notification={id:string;type:string;severity:string;title:string;message:string;sourceRef?:string|null;actionRequired:boolean;status:string;createdAt:string};
type KnowledgeNode={id:string;scope:string;namespace:string;memoryKey:string;content:string;protectedData:boolean;updatedAt:string;tags:string[]};
type MemoryResult={node:KnowledgeNode;score:number;reason:string};
type VoiceSession={id:string;missionId?:string|null;taskId?:string|null;status:string;latestTranscript?:string|null;updatedAt:string};
type CareerAudit={id:string;targetRole:string;readinessScore:number;findings:string;createdAt:string};
type TradeSignal={id:string;symbol:string;side:string;entryPrice:number;stopLoss:number;takeProfit1:number;takeProfit2:number;takeProfit3:number;leverage:number;riskPerTradePct:number;rewardRisk:number;confidence:number;setupScore:number;quickProfitCandidate:boolean;recommendedNotional:number;rationale:string;status:string;createdAt:string};

const SESSION_KEY='aetheris.session';
function readSession():Session|null{try{const raw=sessionStorage.getItem(SESSION_KEY);return raw?JSON.parse(raw) as Session:null;}catch{sessionStorage.removeItem(SESSION_KEY);return null;}}
function writeSession(session:Session){sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));}
async function rotateSession(current:Session):Promise<Session|null>{const response=await fetch('/api/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:current.refreshToken})});if(!response.ok)return null;const auth=await response.json() as AuthResponse;const next={token:auth.accessToken,refreshToken:auth.refreshToken,account:auth.account};writeSession(next);return next;}

export default function App(){
 const [session,setSession]=useState<Session|null>(()=>readSession());
 const [users,setUsers]=useState<User[]>([]),[tasks,setTasks]=useState<OrchestratorTask[]>([]),[approvals,setApprovals]=useState<Approval[]>([]);
 const [providers,setProviders]=useState<ModelProvider[]>([]),[providerHealth,setProviderHealth]=useState<ProviderHealth[]>([]),[budgets,setBudgets]=useState<ProviderBudget[]>([]),[rateLimits,setRateLimits]=useState<RateLimit[]>([]);
 const [invocations,setInvocations]=useState<Invocation[]>([]),[workItems,setWorkItems]=useState<WorkItem[]>([]),[missions,setMissions]=useState<Mission[]>([]),[hosts,setHosts]=useState<Host[]>([]);
 const [proposals,setProposals]=useState<GitHubProposal[]>([]),[mcpServers,setMcpServers]=useState<McpServer[]>([]),[workers,setWorkers]=useState<Worker[]>([]),[tickets,setTickets]=useState<SchedulerTicket[]>([]);
 const [notifications,setNotifications]=useState<Notification[]>([]),[knowledge,setKnowledge]=useState<KnowledgeNode[]>([]),[memoryResults,setMemoryResults]=useState<MemoryResult[]>([]),[voiceSessions,setVoiceSessions]=useState<VoiceSession[]>([]),[careerAudits,setCareerAudits]=useState<CareerAudit[]>([]),[tradeSignals,setTradeSignals]=useState<TradeSignal[]>([]);
 const [emergencyStop,setEmergencyStop]=useState<EmergencyStop|null>(null),[health,setHealth]=useState<Health>('checking'),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[authMessage,setAuthMessage]=useState('');
 const canWriteUsers=useMemo(()=>session?.account.scopes?.includes('users:write')??false,[session]);
 const canControl=useMemo(()=>session?.account.scopes?.includes('orchestrator:write')??false,[session]);
 const healthyProviders=useMemo(()=>providers.filter(p=>p.available).length,[providers]);
 const activeMissions=useMemo(()=>missions.filter(m=>m.status==='ACTIVE').length,[missions]);
 const unreadNotifications=useMemo(()=>notifications.filter(n=>n.status==='UNREAD').length,[notifications]);

 const expireSession=useCallback(()=>{sessionStorage.removeItem(SESSION_KEY);setSession(null);setAuthMessage('Your session ended. Sign in again.');},[]);
 const protectedFetch=useCallback(async(url:string,init:RequestInit={})=>{if(!session)return null;const call=(token:string)=>fetch(url,{...init,headers:{...(init.headers??{}),Authorization:`Bearer ${token}`}});let response=await call(session.token);if(response.status!==401)return response;const rotated=await rotateSession(session);if(!rotated){expireSession();return null;}setSession(rotated);return call(rotated.token);},[session,expireSession]);

 const refresh=useCallback(async()=>{setLoading(true);try{const healthResponse=await fetch('/actuator/health');setHealth(healthResponse.ok?'online':'offline');if(!session)return;
  const urls=['/api/users','/api/orchestrator/tasks','/api/orchestrator/approvals/pending','/api/orchestrator/models/providers','/api/orchestrator/models/provider-health','/api/orchestrator/models/budgets','/api/orchestrator/models/adaptive/rate-limits','/api/orchestrator/invocations','/api/orchestrator/control/emergency-stop','/api/orchestrator/work-queue','/api/orchestrator/missions','/api/orchestrator/hosts','/api/orchestrator/github/proposals','/api/orchestrator/mcp/servers','/api/orchestrator/scheduler/workers','/api/orchestrator/scheduler/tickets/queued','/api/orchestrator/notifications','/api/orchestrator/knowledge/nodes','/api/orchestrator/voice/sessions','/api/orchestrator/career/audits','/api/orchestrator/trading/signals'];
  const setters=[setUsers,setTasks,setApprovals,setProviders,setProviderHealth,setBudgets,setRateLimits,setInvocations,setEmergencyStop,setWorkItems,setMissions,setHosts,setProposals,setMcpServers,setWorkers,setTickets,setNotifications,setKnowledge,setVoiceSessions,setCareerAudits,setTradeSignals] as Array<(v:any)=>void>;
  const responses=await Promise.all(urls.map(u=>protectedFetch(u)));for(let i=0;i<responses.length;i++)if(responses[i]?.ok)setters[i](await responses[i]!.json());setMessage('');
 }catch(error){setHealth('offline');setMessage(error instanceof Error?error.message:'Unable to reach Aetheris');}finally{setLoading(false);}},[session,protectedFetch]);
 useEffect(()=>{refresh();},[refresh]);

 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setAuthMessage('');const form=new FormData(event.currentTarget);const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password')})});if(!response.ok){setAuthMessage('Sign in failed');return;}const auth=await response.json() as AuthResponse;const next={token:auth.accessToken,refreshToken:auth.refreshToken,account:auth.account};writeSession(next);setSession(next);}
 async function logout(){if(session?.refreshToken)await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:session.refreshToken})}).catch(()=>undefined);sessionStorage.removeItem(SESSION_KEY);setSession(null);}
 async function post(url:string,body?:unknown){if(!canControl)return false;const response=await protectedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!response?.ok){const e=await response?.json().catch(()=>({}));setMessage(e?.message??`Action failed (${response?.status??'offline'})`);return false;}await refresh();return true;}
 async function createUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const r=await protectedFetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),email:form.get('email')})});if(r?.ok){event.currentTarget.reset();await refresh();}else setMessage('Could not create user.');}
 async function taskControl(task:OrchestratorTask,action:'pause'|'resume'|'take-control'|'cancel'){if((action==='take-control'||action==='cancel')&&!window.confirm(`${action.replace('-',' ')} ${task.title}?`))return;await post(`/api/orchestrator/control/tasks/${task.id}/${action}`,{reason:`Owner ${action} from Stage 7 Mission Control`});}
 async function toggleStop(){if(!emergencyStop)return;const next=!emergencyStop.active;if(!window.confirm(next?'Engage emergency stop?':'Release emergency stop?'))return;await post(`/api/orchestrator/control/emergency-stop/${next?'engage':'release'}`,{reason:`Owner ${next?'engaged':'released'} from Stage 7 Mission Control`});}
 async function createMission(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);if(await post('/api/orchestrator/missions',{title:f.get('title'),objective:f.get('objective')}))event.currentTarget.reset();}
 async function proposalAction(id:string,action:'request-publish-approval'|'publish'){if(action==='publish'&&!window.confirm('Publish this exact approved GitHub proposal?'))return;await post(`/api/orchestrator/github/proposals/${id}/${action}`);}
 async function grantMcp(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),serverId=String(f.get('serverId')??'');if(!serverId)return;await post(`/api/orchestrator/mcp/servers/${serverId}/grants`,{agentId:f.get('agentId'),capability:f.get('capability'),dataClass:f.get('dataClass')});}
 async function memorySearch(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),q=String(f.get('q')??'').trim();if(!q)return;const r=await protectedFetch(`/api/orchestrator/knowledge/search?q=${encodeURIComponent(q)}&limit=8`);if(r?.ok)setMemoryResults(await r.json());}
 async function tradeDecision(signal:TradeSignal,decision:'accept'|'reject'){const warning=decision==='accept'?`Accept analysis for ${signal.symbol}? This records your decision only. It does NOT place an order.`:`Reject ${signal.symbol} signal?`;if(!window.confirm(warning))return;await post(`/api/orchestrator/trading/signals/${signal.id}/${decision}`);}

 if(!session)return <div className="authShell"><div className="authCard"><div className="brand authBrand"><div className="brandMark">A</div><div><strong>Aetheris</strong><span>Control Plane</span></div></div><p className="eyebrow">SYNTRA + AETHERIS · GOVERNED OPS</p><h1>Sign in</h1><p className="authIntro">Authenticate to the governed personal AI control plane.</p><form onSubmit={login}><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label><button type="submit"><ShieldCheck size={17}/>Sign in</button></form>{authMessage&&<p className="authError">{authMessage}</p>}</div></div>;

 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">A</div><div><strong>Aetheris</strong><span>Control Plane</span></div></div><nav><a className="active"><Gauge size={18}/>Mission Control</a><a><Network size={18}/>Model Fabric</a><a><Boxes size={18}/>Autonomy</a><a><ShieldCheck size={18}/>Security</a><a><Activity size={18}/>Syntra Live</a></nav><div className="identityCard"><span>{session.account.name}</span><strong>{session.account.role}</strong><small>{session.account.email}</small><button onClick={logout}><LogOut size={15}/>Sign out</button></div><div className="stage">AI STAGE 7 <span>Personal Intelligence OS</span></div></aside><main>
  <header><div><p className="eyebrow">SYNTRA + AETHERIS · STAGE 7</p><h1>Personal AI mission control</h1><p>Dependency-aware autonomy, local-first memory, proactive intelligence, adaptive models, voice control, career intelligence and governed market analysis.</p></div><button onClick={refresh} disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/>Refresh</button></header>
  <div className="stage6Banner"><strong>Owner-first safety</strong><span>Windows commands remain simulation-only. Trading signals are analysis-only: Accept records your decision but Stage 7 has no broker execution adapter.</span></div>
  <section className="metrics"><Metric icon={<Activity/>} label="Gateway" value={health==='online'?'Healthy':health==='checking'?'Checking':'Offline'} hint="JWT + owner policy" tone={health}/><Metric icon={<Boxes/>} label="Scheduler" value={`${workers.length} workers`} hint={`${tickets.length} queued tickets`}/><Metric icon={<Network/>} label="Model Fabric" value={`${healthyProviders}/${providers.length||1}`} hint={`${rateLimits.filter(r=>r.blocked).length} rate-limited`}/><Metric icon={<ShieldCheck/>} label="Attention" value={String(unreadNotifications)} hint={`${activeMissions} active missions`}/></section>

  <section className="grid"><article className="panel architecture"><div className="panelHead"><div><p className="eyebrow">PERSONAL INTELLIGENCE PATH</p><h2>Stage 7 architecture</h2></div><span className="liveDot">LIVE</span></div><div className="flow"><Node name="Syntra" meta="Voice + intent"/><Arrow/><Node name="Planner" meta="DAG + memory" glow/><Arrow/><Node name="Scheduler" meta="Priority + backpressure"/><Arrow/><Node name="Agents" meta="Models + tools"/></div></article><article className="panel"><div className="panelHead"><div><p className="eyebrow">OWNER CONTROL</p><h2>Emergency stop</h2></div><StatusPill value={emergencyStop?.active?'ENGAGED':'READY'}/></div><p className="message">{emergencyStop?.reason??'Loading…'}</p><button className="dangerControl" onClick={toggleStop} disabled={!canControl||!emergencyStop}>{emergencyStop?.active?'Release emergency stop':'Engage emergency stop'}</button></article></section>

  <section className="opsGrid"><Panel title="Task control" eyebrow="PAUSE · RESUME · TAKE CONTROL" code={`${tasks.length} tasks`} empty={tasks.length===0}>{tasks.slice(0,8).map(t=><div className="opsItem actionItem" key={t.id}><div><strong>{t.title}</strong><span>{t.activeAgentId??'No active agent'} · {t.mode}</span></div><div className="actionStack"><StatusPill value={t.state}/><div className="actionRow">{t.state==='RUNNING'&&<button className="miniButton" onClick={()=>taskControl(t,'pause')}>Pause</button>}{t.state==='PAUSED'&&<button className="miniButton" onClick={()=>taskControl(t,'resume')}>Resume</button>}{t.state==='RUNNING'&&<button className="miniButton" onClick={()=>taskControl(t,'take-control')}>Take control</button>}{!['COMPLETED','FAILED','CANCELLED'].includes(t.state)&&<button className="miniButton dangerMini" onClick={()=>taskControl(t,'cancel')}>Cancel</button>}</div></div></div>)}</Panel>
   <Panel title="Scheduler & workers" eyebrow="PRIORITY · CONCURRENCY · BACKPRESSURE" code={`${tickets.length} queued`} empty={workers.length===0&&tickets.length===0}>{workers.slice(0,4).map(w=><div className="opsItem" key={w.workerId}><div><strong>{w.workerId}</strong><span>{w.activeLeases}/{w.maxConcurrency} leases · heartbeat {new Date(w.lastHeartbeatAt).toLocaleTimeString()}</span></div><StatusPill value={w.activeLeases>=w.maxConcurrency?'FULL':'READY'}/></div>)}{tickets.slice(0,4).map(t=><div className="opsItem" key={t.id}><div><strong>{t.lane} · priority {t.priority}</strong><span>work {t.workItemId.slice(0,8)}</span></div><StatusPill value={t.state}/></div>)}</Panel></section>

  <section className="opsGrid"><Panel title="Proactive notification center" eyebrow="FAILURES · APPROVALS · PROVIDER DRIFT" code={`${unreadNotifications} unread`} empty={notifications.length===0} action={<button className="miniButton" onClick={()=>post('/api/orchestrator/proactive/scan')} disabled={!canControl}>Scan now</button>}>{notifications.slice(0,8).map(n=><div className="opsItem" key={n.id}><div><strong>{n.title}</strong><span>{n.severity} · {n.message}</span></div><StatusPill value={n.status}/></div>)}</Panel>
   <Panel title="Knowledge graph & memory" eyebrow="LOCAL-FIRST · PROTECTED FILTERING" code={`${knowledge.length} nodes`} empty={knowledge.length===0&&memoryResults.length===0}>{(memoryResults.length?memoryResults.map(r=>r.node):knowledge.slice(0,6)).map(n=><div className="opsItem" key={n.id}><div><strong>{n.memoryKey}</strong><span>{n.scope} · {n.namespace} · {n.protectedData?'PROTECTED':'LOCAL INDEX'}</span></div><StatusPill value={n.protectedData?'PROTECTED':'INDEXED'}/></div>)}<form className="compactForm" onSubmit={memorySearch}><input name="q" required placeholder="Search local memory"/><button type="submit">Search</button></form></Panel></section>

  <section className="opsGrid"><Panel title="Adaptive model fabric" eyebrow="LATENCY · QUALITY · COST · RATE LIMITS" code={`${providerHealth.length} tracked`} empty={providers.length===0}>{providers.map(p=>{const h=providerHealth.find(x=>x.providerId===p.providerId),r=rateLimits.find(x=>x.providerId===p.providerId),b=budgets.find(x=>x.providerId===p.providerId);return <div className="opsItem" key={p.providerId}><div><strong>{p.providerId} · {p.model}</strong><span>{p.local?'LOCAL':'REMOTE'} · {h?.averageLatencyMs??0} ms · ${Number(b?.estimatedCostUsdToday??0).toFixed(4)} today</span></div><StatusPill value={r?.blocked?'RATE LIMITED':h?.circuitOpen?'CIRCUIT OPEN':p.available?'HEALTHY':'OFFLINE'}/></div>})}</Panel>
   <Panel title="Voice sessions" eyebrow="BARGE-IN · DETERMINISTIC PRIORITY COMMANDS" code={`${voiceSessions.length} sessions`} empty={voiceSessions.length===0}>{voiceSessions.slice(0,8).map(v=><div className="opsItem" key={v.id}><div><strong>{v.taskId?`Task ${v.taskId.slice(0,8)}`:'Mission/general voice'}</strong><span>{v.latestTranscript??'No transcript yet'} · {new Date(v.updatedAt).toLocaleTimeString()}</span></div><StatusPill value={v.status}/></div>)}</Panel></section>

  <section className="opsGrid"><Panel title="Trading intelligence" eyebrow="ENTRY · TP · SL · LEVERAGE · OWNER ACCEPTANCE" code={`${tradeSignals.length} signals`} empty={tradeSignals.length===0}>{tradeSignals.slice(0,8).map(s=><div className="opsItem actionItem" key={s.id}><div><strong>{s.symbol} · {s.side}{s.quickProfitCandidate?' · QUICK-PROFIT CANDIDATE':''}</strong><span>Entry {fmt(s.entryPrice)} · SL {fmt(s.stopLoss)} · TP {fmt(s.takeProfit1)} / {fmt(s.takeProfit2)} / {fmt(s.takeProfit3)} · {s.leverage}x · risk {s.riskPerTradePct}% · R:R {s.rewardRisk.toFixed(2)} · confidence {s.confidence.toFixed(1)}% · score {s.setupScore.toFixed(1)}</span><span>{s.rationale}</span></div><div className="actionStack"><StatusPill value={s.status}/>{s.status==='PENDING_ACCEPTANCE'&&<div className="actionRow"><button className="miniButton" onClick={()=>tradeDecision(s,'accept')} disabled={!canControl}>Accept analysis</button><button className="miniButton dangerMini" onClick={()=>tradeDecision(s,'reject')} disabled={!canControl}>Reject</button></div>}</div></div>)}</Panel>
   <Panel title="Career intelligence" eyebrow="RECRUITER READINESS" code={`${careerAudits.length} audits`} empty={careerAudits.length===0}>{careerAudits.slice(0,8).map(a=><div className="opsItem" key={a.id}><div><strong>{a.targetRole}</strong><span>{a.findings}</span></div><StatusPill value={`${a.readinessScore}/100`}/></div>)}</Panel></section>

  <section className="opsGrid"><Panel title="Syntra missions" eyebrow="CONVERSATION + TASK GRAPHS" code={`${missions.length} sessions`} empty={missions.length===0}>{missions.slice(0,6).map(m=><div className="opsItem" key={m.id}><div><strong>{m.title}</strong><span>{m.taskIds.length} tasks · {m.objective}</span></div><StatusPill value={m.status}/></div>)}<form onSubmit={createMission} className="compactForm"><input name="title" required placeholder="Mission title"/><input name="objective" required placeholder="Objective"/><button type="submit" disabled={!canControl}>Create</button></form></Panel>
   <Panel title="Trusted Windows hosts" eyebrow="PAIRING + REPLAY-PROTECTED PROTOCOL" code={`${hosts.length} hosts`} empty={hosts.length===0}>{hosts.slice(0,8).map(h=><div className="opsItem" key={h.id}><div><strong>{h.displayName} · {h.platform}</strong><span>{h.capabilities.join(' · ')||'No capabilities'}</span></div><StatusPill value={h.status}/></div>)}</Panel></section>

  <section className="opsGrid"><Panel title="GitHub proposals" eyebrow="PROPOSE → APPROVE → PUBLISH" code={`${proposals.length} proposals`} empty={proposals.length===0}>{proposals.slice(0,6).map(p=><div className="opsItem actionItem" key={p.id}><div><strong>{p.repository} · {p.path}</strong><span>{p.summary}</span></div><div className="actionStack"><StatusPill value={p.status}/><div className="actionRow"><button className="miniButton" onClick={()=>proposalAction(p.id,'request-publish-approval')} disabled={!canControl}>Request approval</button><button className="miniButton" onClick={()=>proposalAction(p.id,'publish')} disabled={!canControl}>Publish approved</button></div></div></div>)}</Panel>
   <Panel title="MCP trust registry" eyebrow="EXACT SERVER + AGENT GRANTS" code={`${mcpServers.length} servers`} empty={mcpServers.length===0}>{mcpServers.slice(0,6).map(s=><div className="opsItem" key={s.id}><div><strong>{s.displayName}</strong><span>{s.local?'LOCAL':'REMOTE'} · {(s.approvedCapabilities??[]).join(' · ')||'no capabilities'}</span></div><StatusPill value={s.status}/></div>)}<form onSubmit={grantMcp} className="compactForm four"><select name="serverId" required defaultValue=""><option value="" disabled>Server</option>{mcpServers.map(s=><option key={s.id} value={s.id}>{s.displayName}</option>)}</select><input name="agentId" required placeholder="agent id"/><input name="capability" required placeholder="capability"/><input name="dataClass" required placeholder="data class"/><button type="submit" disabled={!canControl}>Grant</button></form></Panel></section>

  <section className="opsGrid"><Panel title="Pending approvals" eyebrow="OWNER GATES" code={`${approvals.length} pending`} empty={approvals.length===0}>{approvals.slice(0,8).map(a=><div className="opsItem" key={a.id}><div><strong>{a.actionType}</strong><span>{a.riskLevel} · task {a.taskId.slice(0,8)}</span></div><StatusPill value={a.status}/></div>)}</Panel><Panel title="Invocation audit" eyebrow="MODEL · TOOL · MCP" code={`${invocations.length} entries`} empty={invocations.length===0}>{invocations.slice(0,8).map(i=><div className="opsItem" key={i.id}><div><strong>{i.kind} · {i.targetId}</strong><span>{i.agentId??'system'} · {new Date(i.startedAt).toLocaleTimeString()}</span></div><StatusPill value={i.status}/></div>)}</Panel></section>

  <article className="panel users"><div className="panelHead"><div><p className="eyebrow">PLATFORM USERS</p><h2>Users</h2></div><code>users:read</code></div>{users.length===0?<div className="empty">No users returned.</div>:<div className="table">{users.map(u=><div className="row" key={u.id}><span className="avatar">{u.name.slice(0,1).toUpperCase()}</span><strong>{u.name}</strong><span>{u.email}</span><code>#{u.id}</code></div>)}</div>}{canWriteUsers&&<form onSubmit={createUser} className="inlineCreate"><label>Name<input name="name" required maxLength={100}/></label><label>Email<input name="email" type="email" required/></label><button type="submit"><Users size={15}/>Create user</button></form>}{message&&<p className="message">{message}</p>}</article>
 </main></div>;
}

function fmt(v:number){return Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:6}):'-';}
function Metric({icon,label,value,hint,tone}:{icon:React.ReactNode;label:string;value:string;hint:string;tone?:Health}){return <article className="metric"><div className="metricIcon">{icon}</div><div><span>{label}</span><strong className={tone?`status ${tone}`:''}>{value}</strong><small>{hint}</small></div></article>;}
function Node({name,meta,glow}:{name:string;meta:string;glow?:boolean}){return <div className={`node ${glow?'glow':''}`}><strong>{name}</strong><span>{meta}</span></div>;}
function Arrow(){return <span className="arrow">→</span>;}
function StatusPill({value}:{value:string}){const safe=value.toLowerCase().replaceAll('_','-').replaceAll(' ','-').replaceAll('/','-');return <span className={`statusPill ${safe}`}>{value.replaceAll('_',' ')}</span>;}
function Panel({title,eyebrow,code,empty,action,children}:{title:string;eyebrow:string;code:string;empty:boolean;action?:React.ReactNode;children:React.ReactNode}){return <article className="panel"><div className="panelHead"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><div className="panelActions">{action}<code>{code}</code></div></div><div className="opsList">{empty?<div className="empty compact">No data yet.</div>:children}</div></article>;}
