server:
  port: 8081

spring:
  application:
    name: aetheris-user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aetheris}
    username: ${SPRING_DATASOURCE_USERNAME:aetheris}
    password: ${SPRING_DATASOURCE_PASSWORD:aetheris}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 60s
      cache-null-values: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Aetheris User Service
    stage: 3
