server:
  port: 8081

spring:
  application:
    name: aetheris-user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aetheris}
    username: ${SPRING_DATASOURCE_USERNAME:aetheris}
    password: ${SPRING_DATASOURCE_PASSWORD:aetheris}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Aetheris User Service
    stage: 1.5
