package io.aetheris.orchestrator.stage9;

import io.aetheris.orchestrator.runtime.*;
import io.aetheris.orchestrator.scheduler.*;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.time.*;import java.util.*;

@Service
public class CapabilityAwareDispatchService {
    private final WorkerCapabilityRepository profiles;private final WorkRequirementRepository requirements;private final WorkerHeartbeatRepository workers;private final SchedulerTicketRepository tickets;private final DurableWorkQueueService queue;private final Duration heartbeatTimeout;
    public CapabilityAwareDispatchService(WorkerCapabilityRepository profiles,WorkRequirementRepository requirements,WorkerHeartbeatRepository workers,SchedulerTicketRepository tickets,DurableWorkQueueService queue,@Value("${aetheris.scheduler.worker-timeout-seconds:45}") long timeout){this.profiles=profiles;this.requirements=requirements;this.workers=workers;this.tickets=tickets;this.queue=queue;this.heartbeatTimeout=Duration.ofSeconds(Math.max(10,timeout));}
    @Transactional public WorkerCapabilityEntity setWorker(String workerId,WorkerCapabilityRequest r){WorkerHeartbeatEntity heartbeat=workers.findById(workerId).orElseThrow(()->new NoSuchElementException("Unknown worker: "+workerId));WorkerCapabilityEntity p=profiles.findById(heartbeat.getWorkerId()).orElseGet(()->new WorkerCapabilityEntity(workerId,r.capabilities(),r.lanes()));p.update(r.capabilities(),r.lanes());return profiles.save(p);}
    @Transactional public WorkRequirementEntity setRequirement(UUID workItemId,WorkRequirementRequest r){queue.getRequired(workItemId);WorkRequirementEntity e=requirements.findById(workItemId).orElseGet(()->new WorkRequirementEntity(workItemId,r.capabilities(),r.lane()));e.update(r.capabilities(),r.lane());return requirements.save(e);}
    public List<WorkerCapabilityEntity> workers(){return profiles.findTop200ByOrderByUpdatedAtDesc();}
    @Transactional public CapabilityDispatchResult dispatch(int leaseSeconds){queue.recoverAbandoned();Set<UUID> ready=new HashSet<>();for(WorkItemEntity i:queue.ready())ready.add(i.getId());Instant cutoff=Instant.now().minus(heartbeatTimeout);for(SchedulerTicketEntity ticket:tickets.findQueuedForUpdate(SchedulerTicketState.QUEUED)){if(!ready.contains(ticket.getWorkItemId()))continue;WorkRequirementEntity req=requirements.findById(ticket.getWorkItemId()).orElse(null);Set<String> caps=req==null?Set.of():req.getCapabilities();String lane=req==null?ticket.getLane():req.getLane();List<WorkerHeartbeatEntity> candidates=new ArrayList<>();for(WorkerHeartbeatEntity worker:workers.findTop100ByOrderByUpdatedAtDesc()){if(!worker.online(cutoff)||worker.getActiveLeases()>=worker.getMaxConcurrency())continue;WorkerCapabilityEntity profile=profiles.findById(worker.getWorkerId()).orElse(null);if(profile==null){if(!caps.isEmpty())continue;}else if(!profile.supports(caps,lane))continue;candidates.add(worker);}if(candidates.isEmpty())continue;candidates.sort((a,b)->{double ua=(double)a.getActiveLeases()/a.getMaxConcurrency(),ub=(double)b.getActiveLeases()/b.getMaxConcurrency();int c=Double.compare(ua,ub);if(c!=0)return c;Instant aa=profiles.findById(a.getWorkerId()).map(WorkerCapabilityEntity::getLastAssignedAt).orElse(null),bb=profiles.findById(b.getWorkerId()).map(WorkerCapabilityEntity::getLastAssignedAt).orElse(null);if(aa==null&&bb!=null)return-1;if(aa!=null&&bb==null)return 1;if(aa!=null){c=aa.compareTo(bb);if(c!=0)return c;}return a.getWorkerId().compareTo(b.getWorkerId());});WorkerHeartbeatEntity chosen=candidates.get(0);WorkItemEntity item=queue.claim(ticket.getWorkItemId(),chosen.getWorkerId(),Math.max(5,Math.min(leaseSeconds,900)));ticket.dispatched();chosen.leaseClaimed();tickets.save(ticket);workers.save(chosen);profiles.findById(chosen.getWorkerId()).ifPresent(p->{p.assigned();profiles.save(p);});return new CapabilityDispatchResult(true,chosen.getWorkerId(),"Capability-compatible fair dispatch with pessimistic ticket lock",ticket,item);}return new CapabilityDispatchResult(false,null,"No ready ticket has an online capability-compatible worker",null,null);}
}
