package io.aetheris.orchestrator.stage9;

import io.aetheris.orchestrator.agent.AgentCatalogService;
import io.aetheris.orchestrator.planner.PlanStepRequest;
import io.aetheris.orchestrator.policy.OperationMode;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class MissionDryRunService {
    private final AgentCatalogService agents;
    public MissionDryRunService(AgentCatalogService agents){this.agents=agents;}
    public MissionDryRunResult evaluate(MissionDryRunRequest r){if(r.steps().isEmpty())return new MissionDryRunResult(false,0,0,0,"LOW",false,0,List.of(),List.of("No steps supplied"),"Dry-run rejected");if(r.steps().size()>24)throw new IllegalArgumentException("Dry-run exceeds 24 steps");Map<String,PlanStepRequest> map=new LinkedHashMap<>();int edges=0;int highRisk=0;boolean approval=false;List<String>warnings=new ArrayList<>();Set<String> evidence=new LinkedHashSet<>();for(PlanStepRequest s:r.steps()){if(s.key()==null||s.key().isBlank()||s.title()==null||s.title().isBlank()||s.command()==null||s.command().isBlank())throw new IllegalArgumentException("Every dry-run step requires key, title and command");if(map.putIfAbsent(s.key(),s)!=null)throw new IllegalArgumentException("Duplicate dry-run step key: "+s.key());if(s.agentId()!=null&&!s.agentId().isBlank())agents.getRequired(s.agentId());String c=s.command().toLowerCase(Locale.ROOT);for(String banned:List.of("withdraw","transfer funds","live trade","disable safety","steal credential","format disk","rm -rf /","bypass approval"))if(c.contains(banned))throw new IllegalArgumentException("Unsafe dry-run command rejected: "+banned);if(c.matches(".*(deploy|publish|delete|driver|registry|admin|purchase|trade|send message|public profile).*")){approval=true;highRisk++;}if(c.matches(".*(research|compare|verify|audit|review|diagnose).*"))evidence.add("source-grounded evidence");if(c.matches(".*(code|implement|fix|build|refactor).*"))evidence.add("tests and diff verification");if(c.matches(".*(deploy|publish|delete|driver|registry|admin).*"))evidence.add("rollback or recovery evidence");edges+=s.dependsOn().size();}
        for(PlanStepRequest s:r.steps())for(String d:s.dependsOn())if(!map.containsKey(d)||d.equals(s.key()))throw new IllegalArgumentException("Invalid dependency "+d+" for "+s.key());assertAcyclic(map);int maxParallelism=estimateParallelism(map);OperationMode mode=r.mode()==null?OperationMode.BALANCED:r.mode();double cost=(mode==OperationMode.ZERO_COST||mode==OperationMode.PRIVATE||!r.allowPaid())?0d:Math.max(0,r.expectedInputTokens())*0.0000025d;String risk=highRisk>=3?"HIGH":highRisk>0?"MEDIUM":"LOW";if(r.protectedData()&&mode!=OperationMode.PRIVATE)warnings.add("Protected data should normally run in PRIVATE mode");if(evidence.isEmpty())evidence.add("completion verification");return new MissionDryRunResult(true,r.steps().size(),edges,maxParallelism,risk,approval,cost,List.copyOf(evidence),List.copyOf(warnings),"Dry-run only: no task, tool, external action or financial execution was created");}
    private int estimateParallelism(Map<String,PlanStepRequest> map){int roots=(int)map.values().stream().filter(s->s.dependsOn().isEmpty()).count();return Math.max(1,roots);}
    private void assertAcyclic(Map<String,PlanStepRequest> map){Set<String> visiting=new HashSet<>(),done=new HashSet<>();for(String k:map.keySet())visit(k,map,visiting,done);}private void visit(String k,Map<String,PlanStepRequest> map,Set<String> visiting,Set<String> done){if(done.contains(k))return;if(!visiting.add(k))throw new IllegalArgumentException("Dependency cycle at "+k);for(String d:map.get(k).dependsOn())visit(d,map,visiting,done);visiting.remove(k);done.add(k);}
}
