package io.aetheris.orchestrator.trading;
import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;
@Entity @Table(name="aetheris_trade_signals")
public class TradeSignalEntity {
 @Id private UUID id;@Column(nullable=false,length=40) private String symbol;@Enumerated(EnumType.STRING) @Column(nullable=false,length=16) private TradeSide side;@Column(nullable=false) private double entryPrice;@Column(nullable=false) private double stopLoss;@Column(nullable=false) private double takeProfit1;@Column(nullable=false) private double takeProfit2;@Column(nullable=false) private double takeProfit3;@Column(nullable=false) private int leverage;@Column(nullable=false) private double riskPerTradePct;@Column(nullable=false) private double rewardRisk;@Column(nullable=false) private double confidence;@Column(nullable=false) private double setupScore;@Column(nullable=false) private boolean quickProfitCandidate;@Column(nullable=false) private double recommendedNotional;@Column(nullable=false,length=4000) private String rationale;@Enumerated(EnumType.STRING) @Column(nullable=false,length=32) private TradeSignalStatus status;@Column(nullable=false) private Instant createdAt;private Instant decidedAt;
 protected TradeSignalEntity(){}public TradeSignalEntity(UUID id,String symbol,TradeSide side,double entry,double sl,double tp1,double tp2,double tp3,int leverage,double risk,double rr,double confidence,double setup,boolean quick,double notional,String rationale,TradeSignalStatus status){this.id=id;this.symbol=symbol;this.side=side;this.entryPrice=entry;this.stopLoss=sl;this.takeProfit1=tp1;this.takeProfit2=tp2;this.takeProfit3=tp3;this.leverage=leverage;this.riskPerTradePct=risk;this.rewardRisk=rr;this.confidence=confidence;this.setupScore=setup;this.quickProfitCandidate=quick;this.recommendedNotional=notional;this.rationale=rationale;this.status=status;this.createdAt=Instant.now();}
 public UUID getId(){return id;}public String getSymbol(){return symbol;}public TradeSide getSide(){return side;}public double getEntryPrice(){return entryPrice;}public double getStopLoss(){return stopLoss;}public double getTakeProfit1(){return takeProfit1;}public double getTakeProfit2(){return takeProfit2;}public double getTakeProfit3(){return takeProfit3;}public int getLeverage(){return leverage;}public double getRiskPerTradePct(){return riskPerTradePct;}public double getRewardRisk(){return rewardRisk;}public double getConfidence(){return confidence;}public double getSetupScore(){return setupScore;}public boolean isQuickProfitCandidate(){return quickProfitCandidate;}public double getRecommendedNotional(){return recommendedNotional;}public String getRationale(){return rationale;}public TradeSignalStatus getStatus(){return status;}public Instant getCreatedAt(){return createdAt;}public Instant getDecidedAt(){return decidedAt;}
 public void accept(){if(status!=TradeSignalStatus.PENDING_ACCEPTANCE)throw new IllegalStateException("Only a pending signal can be accepted");status=TradeSignalStatus.ACCEPTED_ANALYSIS;decidedAt=Instant.now();}public void reject(){if(status!=TradeSignalStatus.PENDING_ACCEPTANCE)throw new IllegalStateException("Only a pending signal can be rejected");status=TradeSignalStatus.REJECTED;decidedAt=Instant.now();}
}
