package io.aetheris.orchestrator.trading;

import io.aetheris.orchestrator.notification.*;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class TradingIntelligenceService {
 private static final String DEFAULT="default";private final TradingRiskPolicyRepository policies;private final TradeSignalRepository signals;private final NotificationService notifications;
 public TradingIntelligenceService(TradingRiskPolicyRepository policies,TradeSignalRepository signals,NotificationService notifications){this.policies=policies;this.signals=signals;this.notifications=notifications;}
 @Transactional public TradingRiskPolicyEntity setPolicy(TradingRiskPolicyRequest r){TradingRiskPolicyEntity p=policies.findById(DEFAULT).orElseGet(()->new TradingRiskPolicyEntity(DEFAULT));p.update(r.riskPerTradePct(),r.maxDailyLossPct(),r.maxLeverage(),r.minRewardRisk());return policies.save(p);}public TradingRiskPolicyEntity policy(){return policies.findById(DEFAULT).orElseGet(()->policies.save(new TradingRiskPolicyEntity(DEFAULT)));}
 @Transactional public TradeSignalEntity analyze(TradeAnalysisRequest r){validate(r);TradingRiskPolicyEntity p=policy();double direction=.55*r.trendScore()+.45*r.momentumScore();TradeSide side=Math.abs(direction)<25?TradeSide.NO_TRADE:(direction>0?TradeSide.LONG:TradeSide.SHORT);double vol=Math.max(.1,Math.min(r.volatilityPct(),20));double confidence=clamp(50+Math.abs(direction)*.42-vol*1.3+(r.confidenceHint()==null?0:(r.confidenceHint()-50)*.25),0,99);double stopPct=Math.max(.35,vol*.8);double entry=r.currentPrice();double fallbackStop=side==TradeSide.SHORT?entry*(1+stopPct/100):entry*(1-stopPct/100);double sl=fallbackStop;if(side==TradeSide.LONG&&r.support()>0&&r.support()<entry)sl=Math.max(r.support(),entry*(1-(stopPct*2)/100));if(side==TradeSide.SHORT&&r.resistance()>entry)sl=Math.min(r.resistance(),entry*(1+(stopPct*2)/100));double riskDistance=Math.max(entry*.002,Math.abs(entry-sl));int sign=side==TradeSide.SHORT?-1:1;double tp1=entry+sign*riskDistance*1.25,tp2=entry+sign*riskDistance*1.8,tp3=entry+sign*riskDistance*2.5;double rr=side==TradeSide.NO_TRADE?0:Math.abs(tp3-entry)/riskDistance;double setup=side==TradeSide.NO_TRADE?Math.max(0,45-Math.abs(direction)/2):clamp(52+Math.abs(direction)*.35+confidence*.18-vol*1.2,0,99);if(rr<p.getMinRewardRisk())setup=Math.max(0,setup-25);int leverage=side==TradeSide.NO_TRADE?1:Math.max(1,Math.min(p.getMaxLeverage(),(int)Math.floor(Math.max(1,3.5/vol))));double riskCapital=Math.max(0,r.accountBalance())*(p.getRiskPerTradePct()/100);double qty=riskDistance<=0?0:riskCapital/riskDistance;double notional=Math.min(qty*entry,Math.max(0,r.accountBalance())*leverage);double tp1Pct=Math.abs(tp1-entry)/entry*100;boolean quick=side!=TradeSide.NO_TRADE&&setup>=80&&confidence>=75&&tp1Pct<=Math.max(.8,vol*1.25);TradeSignalStatus status=side==TradeSide.NO_TRADE?TradeSignalStatus.NO_TRADE:TradeSignalStatus.PENDING_ACCEPTANCE;String rationale="Direction score "+round(direction)+", confidence "+round(confidence)+"%, volatility "+round(vol)+"%, R:R "+round(rr)+". "+(quick?"High-momentum/short-horizon candidate; owner acceptance is still mandatory. ":"")+"Analysis only: no order has been placed and profit is not guaranteed.";TradeSignalEntity signal=signals.save(new TradeSignalEntity(UUID.randomUUID(),r.symbol().trim().toUpperCase(Locale.ROOT),side,entry,side==TradeSide.NO_TRADE?0:sl,side==TradeSide.NO_TRADE?0:tp1,side==TradeSide.NO_TRADE?0:tp2,side==TradeSide.NO_TRADE?0:tp3,leverage,p.getRiskPerTradePct(),rr,confidence,setup,quick,notional,rationale,status));if(status==TradeSignalStatus.PENDING_ACCEPTANCE&&setup>=75)notifications.publish("trade-signal:"+signal.getId(),"TRADE_SIGNAL",quick?NotificationSeverity.HIGH:NotificationSeverity.WARNING,(quick?"High-score trading signal":"Trading signal")+": "+signal.getSymbol(),"Review direction, entry, TP/SL, leverage, risk and reasoning. Explicit acceptance is required; Stage 7 has no broker execution adapter.",signal.getId().toString(),true);return signal;}
 public List<TradeSignalEntity> recent(){return signals.findTop100ByOrderByCreatedAtDesc();}
 @Transactional public TradeDecisionResult accept(UUID id){TradeSignalEntity s=required(id);s.accept();signals.save(s);return new TradeDecisionResult(s,"NOT_EXECUTED","Signal analysis accepted by owner. Stage 7 deliberately has no live execution adapter; acceptance does not place an order.");}
 @Transactional public TradeDecisionResult reject(UUID id){TradeSignalEntity s=required(id);s.reject();signals.save(s);return new TradeDecisionResult(s,"REJECTED","Signal rejected; no order was placed.");}
 public TradeSignalEntity required(UUID id){return signals.findById(id).orElseThrow(()->new NoSuchElementException("Unknown trade signal: "+id));}
 private void validate(TradeAnalysisRequest r){if(r.symbol()==null||r.symbol().isBlank())throw new IllegalArgumentException("Symbol is required");if(r.currentPrice()<=0)throw new IllegalArgumentException("Current price must be positive");if(r.trendScore()<-100||r.trendScore()>100||r.momentumScore()<-100||r.momentumScore()>100)throw new IllegalArgumentException("Trend and momentum scores must be between -100 and 100");if(r.volatilityPct()<0)throw new IllegalArgumentException("Volatility cannot be negative");}
 private double clamp(double v,double min,double max){return Math.max(min,Math.min(v,max));}private double round(double v){return Math.round(v*100d)/100d;}
}
